### ISSUE TITLE
Shits fucked in FF

### ISSUE THREAD

**Issue by Bergalerga** [Bergalerga/Millionairedinjo#7]
a, b, c, d key events not triggering coloring of answers in firefox

**Comment by hakloev** [comment]
The browser incompatibility is a known bug, ref commit 3bfad6e. Due to the use of wav and mp4 sounds, either Safari or Firefox will work. That key events, not triggers, on the other hand, is a new bug. Maybe this is due to the fact that we changed from `e.which` to `e.keyCode` for identifying events?

**Comment by espehel** [comment]
That is correct. My bad. Turns out FF uses charCode and webkit based browser uses keyCode, that explains why to use "which". wav sound files works in my safari :o

**Comment by hakloev** [comment]
Strange, I can't seem to get wav working in Safari :(
